allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: true
  workerd: false
confirmModulesPurge: false
